version: "3"
services:
  database:
    image: "sameersbn/mysql:latest"
    environment:
      DB_NAME: staytus
      DB_USER: staytus
      DB_PASS: staytus
    volumes:
      - "~/Temp/staytus-db:/var/lib/mysql"
  staytus:
    image: staytus
    links:
      - database
    ports:
      - "5000:5000"
    environment:
      CREATE_DB: 0
      DB_HOST: database
      DB_PASSWORD: staytus
      DEBUG: "true"
      LOGLEVEL: WARN
      RAILS_ENV: production
      SETTING_STAYTUS_THEME: lime
      FORCE_SSL: "0"
      WEBHOOK_URL: 
      SETTING_STAYTUS_SMTP_HOSTNAME: smtp.sendgrid.net
      SETTING_STAYTUS_SMTP_USERNAME: apikey
      SETTING_STAYTUS_SMTP_PASSWORD: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      SETTING_STAYTUS_SMTP_PORT: 587
      SETTING_STAYTUS_SMTP_STARTTLS: "1"
